#!/bin/sh
site=https://github.com/racaljk/hosts

thisname=${0##*/}

HOSTS=/etc/hosts
REMOTE="hosts.rmt"

MAIN="https://raw.githubusercontent.com/racaljk/hosts/master/hosts"
MIRROR="https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts"
HOSTS_URL="$MAIN"

NET_TOOL="wget"
QWGET=
QCURL=

usage() {
    cat >&2 <<EOL
提示:
  可使用 crontab 定时执行脚本 (请确保 sudo 无需输入密码)

用法: $thisname [选项]...
从 $site 获取更新的 hosts 文件

选项:
  -c, --curl             使用 curl 下载
  -m, --mirror           使用镜像下载
  -q, --quiet            静默下载
  -h, --help             显示帮助信息并退出

示例: $thisname -cmq
EOL
}

hosts_get() {
    if [ "$NET_TOOL" = "wget" ]; then
        "$NET_TOOL" $QWGET "$HOSTS_URL" -O "$REMOTE"
    else
        # use curl
        "$NET_TOOL" $QCURL "$HOSTS_URL" -o "$REMOTE"
    fi
}

hosts_update() {
    local local="$1"
    local rmt="$2"
    local tmp="hosts.swp"
    local begin="# Copyright (c) 2014"
    local end="# Modified hosts end"

    sed -e "s/localhost/`hostname`/g" "$rmt" > "$tmp"
    rm -f "$rmt"

    # check if racaljk hosts, or do nothing
    if cat "$local" | grep -q racaljk; then
        sed -e "/$begin/,/$end/d" "$local" >> "$tmp"
    fi

    sudo mv "$tmp" "$local"
}

CMD=`getopt -o cmqh1 --long curl,mirror,quiet,help -n "$thisname" -- "$@"` || \
    exit 1

eval set -- "$CMD"

while true; do
    case "$1" in
        -c|--curl)
            NET_TOOL=curl
            shift
            ;;
        -m|--mirror)
            HOSTS_URL="$MIRROR"
            shift
            ;;
        -q|--quiet)
            QWGET=-q
            QCURL=-s
            shift
            ;;
        -h|-1|--help)
            usage
            exit 0
            shift
            ;;
        --)
            shift
            break
            ;;
    esac
done

hosts_get
hosts_update "$HOSTS" "$REMOTE"
